#
# Makefile for the Linux kernel device drivers.
#
obj-y				+= proxm_class/
obj-y				+= cm3623/
obj-y				+= al3010/
obj-$(CONFIG_SENSORS)		+= sensors_class.o
obj-$(CONFIG_SENSORS_SSC)	+= sensors_ssc.o
