ccflags-$(CONFIG_POWER_SUPPLY_DEBUG) := -DDEBUG

obj-$(CONFIG_BATTERY_ASUS)   	+= axc_chargerfactory.o
obj-$(CONFIG_BATTERY_ASUS)   	+= axc_PM8921Charger.o
obj-$(CONFIG_MAXIM_8934_CHARGER)   	+= axc_Maxim8934Charger.o
obj-$(CONFIG_BATTERY_ASUS)   	+= axc_DummyCharger.o

