#
# Pressure Slaves to MPUxxxx
#
obj-$(CONFIG_MPU_SENSORS_BMA085) += inv_mpu_bma085.o
inv_mpu_bma085-objs +=	bma085.o

EXTRA_CFLAGS += -Idrivers/misc/mpu3050
EXTRA_CFLAGS += -D__C99_DESIGNATED_INITIALIZER
